### ISSUE TITLE
Something like emoji utility in Powercord

### ISSUE THREAD

**Issue by Xeiv** [vizality-community/suggestions#10]
**Description**
It can clone emotes to other servers or create emotes using images sent in the chat using the context menu or commands.

**Expected behavior**
Right click emote, hover over clone to in context menu, select server from the list of servers. 
do .cloneemote for example and type the emote to clone it to default server set in the settings.
Right click image in chat, hover over create emote and select the server it will be created in and show a modal where you enter the name.

**Additional context**
Well the one in powercord has more features but there are the only two that are the most useful in my opinion.

----

- [✓] I have checked to make sure a similar request has not already been proposed
- [✓] I have checked to made sure this request complies with Vizality's [guidelines](https://github.com/vizality/vizality-community/blob/master/GUIDELINES.md)

**Comment by resucutie** [comment]
ah yes, one of the best powercord plugins in my opinion.

i'll not port the original version to vizality, instead i gonna make my own version of it.
have a nice day ;-)

**Comment by resucutie** [comment]
Done. [Check it out here](https://github.com/A-User-s-Discord-Plugins/emoji-util)
It doesn't have commands but i think that nobody uses them
