### ISSUE TITLE
Better PIP

### ISSUE THREAD

**Issue by resucutie** [vizality-community/suggestions#12]
**Description**
I gonna be honest, streaming in discord is easy to setup, **but it is annoying to watch in Picture in Picture**
Most of times you wanna watch two streams at the same time, but you can't get attention to both streams
And for making things worse, you can't watch multiple streams
It would be nice if we can make using Picture in Picure  a better experience

**Expected behavior**
There are some suggestions that we can do to improve it:
1. When hovered, it can show what it is behind
   - ![VrpX2HliN9](https://user-images.githubusercontent.com/27961224/107296209-abaaf300-6a4f-11eb-864a-8cb16de4fb20.gif)
2. Make it completly resizable
3. Show multiple streams in picture in picutre mode in this way
   - ![image](https://user-images.githubusercontent.com/27961224/107296390-080e1280-6a50-11eb-9c4f-57e5d77f23a3.png)
4. Make it 100% free draggable
Those are my ideas, If somebody has a better one i'll be proud of that

----

- [x] I have checked to make sure a similar request has not already been proposed
- [x] I have checked to made sure this request complies with Vizality's [guidelines](https://github.com/vizality-community/guidelines)

Just extra notes: Yeah, it is simmilar to #11 but its more focused on Picture In Picutre

**Comment by Snapperito** [comment]
Maybe could be included with #11?

**Comment by resucutie** [comment]
Maybe as a complement?

**Comment by resucutie** [comment]
I've decided to close since I am no longer interested with Vizality (and idk about the state of the project). If you're still up to reopen it, go ahead
