### ISSUE TITLE
Expanded Emoticons

### ISSUE THREAD

**Issue by tropicaaal** [vizality-community/suggestions#14]
**Description**
Discord currently offers a few builtin commands for sending emoticons such as /shrug, /tableflip and /unflip. I suggest that this functionality be expanded with a plugin to include many more of these emoticon types. Could even have an option to add custom ones.

**Expected behavior**
n/a

**Additional context**
https://en.wikipedia.org/wiki/List_of_emoticons

----

- [x] I have checked to make sure a similar request has not already been proposed
- [x] I have checked to made sure this request complies with Vizality's [guidelines](https://github.com/vizality-community/guidelines)

**Comment by Snapperito** [comment]
I would assume it would function similarly to https://github.com/davidjcralph/kaomoji?

**Comment by valentinegb** [comment]
Working on this here: https://github.com/Controlfreak707/Expanded-Emoticons I'll send it on the server when it's ready for use.

**Comment by valentinegb** [comment]
Basically done, this issue can be closed now. I can and probably will add more emoticons in the future, but for now, there's plenty.
