### ISSUE TITLE
Censors images in NSFW channels automatically

### ISSUE THREAD

**Issue by DanKGooGLy** [vizality-community/suggestions#7]
**Description**
It censors images in NSFW channels, basically just marking them as spoilers.

**Expected behavior**
When an image is sent, it is automatically blurred

----

 - [x] I have checked to make sure a similar request has not already been proposed
 - [x] I have checked to made sure this request complies with Vizality's [guidelines](https://github.com/vizality/vizality-community/blob/master/GUIDELINES.md)

**Comment by dperolio** [comment]
Should be a fairly easy one to do, I might be willing.

**Comment by dperolio** [comment]
Oh, I forgot, I already add utility classes to the chat area, one of which is `vz-isNsfwChannel`, so you could easily do this with CSS only. Probably a better idea for a Mini-theme or Snippet, rather than a plugin.

**Comment by sepruko** [comment]
If you're going to add these utility classes, maybe just make in an inbuilt option in Vizality?

**Comment by dperolio** [comment]
Yeah, very possible. I intend to have quite a few settings options, split into categories. Though, for this particular instance, I think it would probably be better served as a Snippet, but we'll see.
